# Generated by Django 5.2.8 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropDiseaseDetection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='prevention',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
