# Generated by Django 5.2.8 on 2026-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(db_index=True, max_length=100)),
                ('forecast_date', models.DateField()),
                ('predicted_price', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(choices=[('arima', 'ARIMA'), ('sarimax', 'SARIMAX'), ('lgbm', 'LightGBM'), ('ensemble', 'Ensemble')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=20)),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('trained_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('commodity', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('commodity', 'date')},
            },
        ),
    ]
