# Generated by Django 5.2.8 on 2026-03-09 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction ID sent to eSewa.', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base product/service amount.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax component.', max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge.', max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, help_text='Delivery charge.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of all amount fields.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('esewa_ref_id', models.CharField(blank=True, help_text='Reference ID from eSewa after success.', max_length=100, null=True)),
                ('esewa_raw_response', models.JSONField(blank=True, help_text='Full raw eSewa verification API response.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
