# Generated by Django 5.2.8 on 2026-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid (Unlimited)')], default='FREE', max_length=20),
        ),
    ]
