# Generated by Django 5.2.8 on 2026-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_subscription_options_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
