# Generated by Django 5.2.8 on 2026-01-26 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('verify', 'Verify'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['-timestamp'], name='admin_activ_timesta_2d3e73_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='admin_activ_admin_u_335dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='admin_activ_action_21303d_idx'),
        ),
        migrations.AlterModelTable(
            name='adminactivitylog',
            table='admin_activity_logs',
        ),
    ]
