# Generated by Django 5.2.8 on 2025-12-27 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_avatar_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('crop_types', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='nepali', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
