# Generated by Django 5.2.8 on 2025-12-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityname', models.CharField(max_length=200, unique=True)),
                ('commodityunit', models.CharField(blank=True, max_length=50, null=True)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['commodityname'],
            },
        ),
        migrations.CreateModel(
            name='DailyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_predictor.masterproduct')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
