# Generated by Django 5.2.8 on 2025-12-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=150)),
                ('commodity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'commodity_name'],
                'unique_together': {('commodity_name', 'date')},
            },
        ),
    ]
