# Generated by Django 5.2.8 on 2026-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypricehistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailypricehistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
